development:
  adapter: postgresql
  encoding: utf8
  database: boulder_app_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: boulder_app_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: boulder_app
  pool: 5

