# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Grade.create(name: 'V0' , score: 10, route_type: "boulder")
Grade.create(name: 'V0+' , score: 13, route_type: "boulder")
Grade.create(name: 'V1-' , score: 16, route_type: "boulder")
Grade.create(name: 'V1' , score: 20, route_type: "boulder")
Grade.create(name: 'V1+' , score: 23, route_type: "boulder")
Grade.create(name: 'V2-' , score: 26, route_type: "boulder")
Grade.create(name: 'V2' , score: 30, route_type: "boulder")
Grade.create(name: 'V2+' , score: 33, route_type: "boulder")
Grade.create(name: 'V3-' , score: 36, route_type: "boulder")
Grade.create(name: 'V3' , score: 40, route_type: "boulder")
Grade.create(name: 'V3+' , score: 43, route_type: "boulder")
Grade.create(name: 'V4-' , score: 46, route_type: "boulder")
Grade.create(name: 'V4' , score: 50, route_type: "boulder")
Grade.create(name: 'V4+' , score: 53, route_type: "boulder")
Grade.create(name: 'V5-' , score: 56, route_type: "boulder")
Grade.create(name: 'V5' , score: 60, route_type: "boulder")
Grade.create(name: 'V5+' , score: 63, route_type: "boulder")
Grade.create(name: 'V6-' , score: 66, route_type: "boulder")
Grade.create(name: 'V6' , score: 70, route_type: "boulder")
Grade.create(name: 'V6+' , score: 73, route_type: "boulder")
Grade.create(name: 'V7-' , score: 76, route_type: "boulder")
Grade.create(name: 'V7' , score: 80, route_type: "boulder")
Grade.create(name: 'V7+' , score: 83, route_type: "boulder")
Grade.create(name: 'V8-' , score: 86, route_type: "boulder")
Grade.create(name: 'V8' , score: 90, route_type: "boulder")
Grade.create(name: 'V8+' , score: 93, route_type: "boulder")
Grade.create(name: 'V9-' , score: 96, route_type: "boulder")
Grade.create(name: 'V9' , score: 100, route_type: "boulder")
Grade.create(name: 'V9+' , score: 103, route_type: "boulder")
Grade.create(name: 'V10-' , score: 106, route_type: "boulder")
Grade.create(name: 'V10' , score: 110, route_type: "boulder")
Grade.create(name: 'V10+' , score: 113, route_type: "boulder")
Grade.create(name: 'V11-' , score: 116, route_type: "boulder")
Grade.create(name: 'V11' , score: 120, route_type: "boulder")
Grade.create(name: 'V11+' , score: 123, route_type: "boulder")
Grade.create(name: 'V12-' , score: 126, route_type: "boulder")
Grade.create(name: 'V12' , score: 130, route_type: "boulder")
Grade.create(name: 'V12+' , score: 133, route_type: "boulder")
